const QUERY_LIST = "QUERY_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_FILE_HASH = "CHANGE_FILE_HASH"
const CHANGE_FILE_NAME = "CHANGE_FILE_NAME"
const CHANGE_FILE_SIZE = "CHANGE_FILE_SIZE"
const CHANGE_APP_KEY = "CHANGE_APP_KEY"
const INIT_APP_LIST = "INIT_APP_LIST"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"

export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_FILE_HASH,
  CHANGE_FILE_NAME,
  CHANGE_FILE_SIZE,
  CHANGE_APP_KEY,
  INIT_APP_LIST,
  CHANGE_SAVE_LOADING,
}