const QUERY_LIST = "QUERY_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"

const SET_NAME = "SET_NAME"
const SET_TYPE = "SET_TYPE"
const SET_PASSWORD = "SET_PASSWORD"
const SET_RE_PASSWORD = "SET_RE_PASSWORD"




export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_SAVE_LOADING,

  SET_NAME,
  SET_TYPE,
  SET_PASSWORD,
  SET_RE_PASSWORD,
}