const CHANGE_LOGIN_LOADING = 'CHANGE_LOGIN_LOADING';
const CHANGE_LOGIN_NAME = 'CHANGE_LOGIN_NAME';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
const CHANGE_UKEY_LOADING = 'CHANGE_UKEY_LOADING';

export {
  CHANGE_LOGIN_LOADING,
  CHANGE_LOGIN_NAME,
  CHANGE_PASSWORD,
  CHANGE_UKEY_LOADING,
}