const CHANGE_LOGIN_LOADING = 'CHANGE_LOGIN_LOADING';
const CHANGE_LOGIN_NAME = 'CHANGE_LOGIN_NAME';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export {
  CHANGE_LOGIN_LOADING,
  CHANGE_LOGIN_NAME,
  CHANGE_PASSWORD

}