const QUERY_LIST = "QUERY_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"
const SET_APP_ID = "CHANGE_EDIT_TITLE"
const SCHANGE_VISIBLE = "SCHANGE_VISIBLE"

export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  SET_APP_ID,
  CHANGE_SAVE_LOADING,
  SCHANGE_VISIBLE,
}